### ISSUE TITLE
Read canned responses from an Asset

### ISSUE THREAD

**Issue by ldvlgr** [mschmitt19/plugin-flex-chat-canned-reponses#6]
To allow users to deploy updated canned messages (but not having to redeploy the plugin), this plugin should load the messages from an Asset via a function. 
See example https://github.com/twilio-professional-services/outbound-callerid/tree/main/serverless/functions

**Comment by mschmitt19** [comment]
Thanks for the feedback Ludo! Just addressed this in [this PR](https://github.com/mschmitt19/plugin-flex-chat-canned-reponses/pull/7).
